FROM scala

RUN apt-get update \
 && DEBIAN_FRONTEND="noninteractive" apt-get install -y docker.io \
 && rm -rf /var/lib/apt/lists/*

COPY build/distributions/invoker.tar ./
RUN tar xf invoker.tar && \
rm -f invoker.tar

COPY init.sh /
RUN chmod +x init.sh

EXPOSE 8080
CMD ["init.sh", "0"]