#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# Start with a new VM
if [ -d ".vagrant" ]; then
  vagrant destroy
fi

vagrant plugin install vagrant-disksize
vagrant up
