{
 "title": "OpenWhisk - Global Metrics",
 "tags": [ "openwhisk" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Successful Activations",
   "type": "singlestat",
   "description": "Total number of successful activations executed",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_status{status=\"success\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Cold Starts",
   "type": "singlestat",
   "description": "Total number of cold starts",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_coldStarts_total[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Internal Errors",
   "type": "singlestat",
   "description": "Total number of error due to Runtime implementation",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_status{status=\"internal_error\"}[${__range_s}s]))"
    }
   ]
  },
  { "title": "Related Dashboards", "type": "dashlist", "gridPos": { "h": 3, "w": 11, "x": 12, "y": 0 } },
  {
   "title": "Activations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_activations_total[1m]))"
    }
   ]
  },
  {
   "title": "wait time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openwhisk_action_waitTime_seconds_sum[30s]) * 1000 / rate(openwhisk_action_waitTime_seconds_count[30s]) ",
     "legendFormat": "{{namespace}}/{{action}}"
    }
   ]
  }
 ]
}