{
 "title": "Openwhisk - Action Performance Metrics",
 "description": "Action performance metrics available for the users of Openwhisk.",
 "tags": [ "openwhisk" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": "query_result(sum(increase(openwhisk_action_activations_total[$__range])) by (region) > 0)"
   },
   {
    "name": "stack",
    "query": "query_result(sum(increase(openwhisk_action_activations_total[$__range])) by (stack) > 0)"
   },
   {
    "name": "initiator",
    "query": "query_result(sum(increase(openwhisk_action_activations_total{namespace=~\"$namespace\"}[$__range])) by (initiator) > 0)"
   },
   {
    "name": "namespace",
    "query": "query_result(sum(increase(openwhisk_action_activations_total[$__range])) by (namespace))"
   },
   {
    "name": "action",
    "query": "query_result(sum(increase(openwhisk_action_activations_total{namespace=~\"$namespace\",initiator=~\"$initiator\"}[$__range])) by (action) > 0)"
   },
   {
    "name": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total activations",
   "type": "singlestat",
   "description": "Total number of activation in the selected time interval",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_activations_total{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Successful activations",
   "type": "singlestat",
   "description": "Total number of successful activations executed",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_status{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",status=\"success\",initiator=~\"$initiator\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error activations",
   "type": "singlestat",
   "description": "Total number of error activations in the selected time interval",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_status{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",status!=\"success\",initiator=~\"$initiator\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Cold starts",
   "type": "singlestat",
   "description": "Total number of cold starts in the selected time interval",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_coldStarts_total{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$__range]))"
    }
   ]
  },
  { "title": "General gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Activation success rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_status{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",status=\"success\",initiator=~\"$initiator\"}[$__range])) * 100 / sum(increase(openwhisk_action_status{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Action duration current",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(openwhisk_action_duration_seconds_sum{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$__range]) / rate(openwhisk_action_duration_seconds_count{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\"}[$__range]) > 0)"
    }
   ]
  },
  {
   "title": "Action wait time current",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(openwhisk_action_waitTime_seconds_sum{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$__range]) / rate(openwhisk_action_waitTime_seconds_count{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\"}[$__range]) > 0)"
    }
   ]
  },
  {
   "title": "Action memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "openwhisk_action_memory{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Activation result graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Activations [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "activations" }
   ],
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_activations_total{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Activation success [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "activations" }
   ],
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_status{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",status=\"success\",initiator=~\"$initiator\"}[$interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Activation errors [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "activations" }
   ],
   "targets": [
    {
     "expr": "sum(increase(openwhisk_action_status{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",status!=\"success\",initiator=~\"$initiator\"}[$interval])) by (action,status)",
     "legendFormat": "{{action}}: {{status}}"
    }
   ]
  },
  { "title": "Duration graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Duration [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(openwhisk_action_duration_seconds_sum{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$interval]) * 1000 / rate(openwhisk_action_duration_seconds_count{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$interval]) ",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Init Time Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Initialization time [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(openwhisk_action_initTime_seconds_sum{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$interval]) * 1000 / rate(openwhisk_action_initTime_seconds_count{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$interval]) ",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Wait time [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(openwhisk_action_waitTime_seconds_sum{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$interval]) * 1000 / rate(openwhisk_action_waitTime_seconds_count{region=~\"$region\",stack=~\"$stack\",namespace=~\"$namespace\",action=~\"$action\",initiator=~\"$initiator\"}[$interval]) ",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}